dataset: {min_intersection_ratio: 0.8, number_of_external_vehicle_samples: 1000, positive_negative_ratio: 1,
  use_external_vehicle_samples: true}
preprocessing:
  cells_per_block: {x: 4, y: 4}
  input_shape: {x: 128, y: 80}
  orientations: 9
  pixels_per_cell: {x: 16, y: 12}
svm: {C: 3, bagging: false, n_estimators: 1}
